### ISSUE TITLE
Check migration of canceled/trashed actions

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler-custom-tables#7]
At the moment, canceled actions (which use post status `trash` with `ActionScheduler_wpPostStore`) are not being migrated to the new data store. This is likely intentionally, but worth double checking.

It may also make sense for these actions to be migrated so that they are available for debugging purposes.

**Comment by thenbrent** [comment]
Related error:

```
Fatal error: Uncaught Error: Call to undefined method ActionScheduler_NullAction::get_status() in /action-scheduler-custom-tables/src/Migration/Action_Migrator.php:18
Stack trace:
#0 /action-scheduler-custom-tables/src/Migration/Migration_Runner.php(44): Action_Scheduler\Custom_Tables\Migration\Action_Migrator->migrate('13022')
#1 /action-scheduler-custom-tables/src/Migration/Migration_Runner.php(35): Action_Scheduler\Custom_Tables\Migration\Migration_Runner->migrate_actions(Array)
#2 /action-scheduler-custom-tables/src/WP_CLI/Migration_Command.php(70): Action_Scheduler\Custom_Tables\Migration\Migration_Runner->run(250)
#3 [internal function]: Action_Scheduler\Custom_Tables\WP_CLI\Migration_Command->migrate(Array, Array in /action-scheduler-custom-tables/src/Migration/Action_Migrator.php on line 18
```

**Comment by rrennick** [comment]
Everything migrated for me

<img width="474" alt="screen shot 2019-03-04 at 11 15 22 am" src="https://user-images.githubusercontent.com/343847/53742392-eae96600-3e6e-11e9-8e7a-e0c94d28a3a9.png">

```shell
mysql> select status, count(*) from wp_actionscheduler_actions group by status;
+----------+----------+
| status   | count(*) |
+----------+----------+
| canceled |        4 |
| complete |      330 |
| failed   |        1 |
| pending  |        2 |
+----------+----------+
```

`Fatal error: Uncaught Error: Call to undefined method ActionScheduler_NullAction::get_status() in /action-scheduler-custom-tables/src/Migration/Action_Migrator.php:18`

This looks like it's been fixed with this try/catch https://github.com/Prospress/action-scheduler-custom-tables/blob/master/src/Migration/Action_Migrator.php#L19:L21

Closing this one.
